name: scipack_dev
channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - openalea.core
  - numpy
  - matplotlib
  - ipykernel
  - configobj
  - pip
  - pip:
      - -e '..[test,dev,doc]'