name: scipack_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  - python
  - openalea.core
  - QtPy
  - PyQt
  - matplotlib-base
  - pip
  - pip:
      - -e '..[test,dev,doc]'