{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set license = pyproject.get('project').get('license') %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda-environment', {}).get('dependencies',[]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  string: py{{ PY_VER }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}

  build:
    - {{ compiler("cxx") }}

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}


test:
  requires:
    - openalea.core
    - openalea.visualea
    - pytest
    - nbmake
    - setuptools
    - imageio
    - QtPy
    - PyQt
    - scipy
  imports:
    - openalea.oapylab
  source_files:
    - test/test_stdlib/test*
    - test/test_numpy/test*
    - test/test_image/test*
    - test/test_pylab/test*
  commands:
    - pytest -v --ignore=test/test_image/test_inrimage.py --ignore=test/test_image/test_morpho.py --ignore=test/test_image/test_read_sequence.py --ignore=test/test_pylab/test_pylab_nodes.py

about:
  home: {{ home }}
  summary: {{ description }}
  license: {{ license }}

extra:
  recipe-maintainers:
    - pradal
    - baugetfa